from django.contrib import admin
from .models import *
admin.site.register( RotaryScrewCompressor)
admin.site.register( ReciprocatingCompressor)
admin.site.register( ScrollCompressor)
admin.site.register( TurboCompressor)
admin.site.register( AirDryerEquipement)
admin.site.register( FilterEquipement)
admin.site.register( AirReceiverEquipement)
admin.site.register( NitrogenGeneratorEquipement)
admin.site.register( DODInkJet)
admin.site.register( CIJInkJet)
admin.site.register( TIJInkJet)
admin.site.register( LaserMarkingInkJet)
admin.site.register( SteelStanless)
admin.site.register( WaterInvesemetEquipement)
admin.site.register( WaterInvesemetSystem)